// Live product semantics for topology constraints.
// Authority: docs/contracts/repository-topology.md

export const authorityTopologyEdges = [
  ['docs/contracts/**', 'contexts/*/src/contract/*'],
  ['docs/contracts/repository-topology.md', 'docs/generated/authority-graph.json'],
  ['docs/contracts/api-events.md', 'apps/workspace-api/generated/openapi.json'],
] as const;

export const allowedImportTopologyEdges = [
  ['apps/web', 'contexts/*/src/contract/*'],
  ['apps/worker', 'contexts/*/src/contract/*'],
  ['contexts/scheduler', 'contexts/note-model'],
  ['contexts/context-assembly', 'contexts/note-model'],
  ['contexts/context-assembly', 'contexts/memory'],
  ['contexts/ai-operations', 'contexts/note-model'],
  ['contexts/ai-operations', 'contexts/memory'],
] as const;

export const allowedRuntimeTopologyEdges = [
  ['apps/web', 'apps/worker'],
  ['apps/worker', 'cloudflare-agents'],
  ['apps/worker note structure route handler', 'apps/worker scheduler runtime flow'],
  ['apps/worker scheduler runtime flow', 'SchedulerNoteSnapshotPort'],
  ['SchedulerNoteSnapshotPort', 'Turso canonical sections'],
  ['SchedulerNoteSnapshotPort', 'Agent-local dirty section marks'],
  ['StructureJob queue', 'apps/worker structure job processor flow'],
  ['apps/worker structure job processor flow', 'StructureJobWorkQueuePort'],
  ['apps/worker structure job processor flow', 'apps/worker structure job Agent handler'],
  ['StructureJobWorkQueuePort', 'Agent-local StructureJob queue'],
  ['apps/worker structure job Agent handler', 'apps/worker context assembly runtime flow'],
  ['apps/worker structure job Agent handler', 'apps/worker structure job operation orchestration flow'],
  ['apps/worker context assembly runtime flow', 'contexts/context-assembly contract'],
  ['apps/worker context assembly runtime flow', 'ContextAssemblyTargetSnapshotPort'],
  ['apps/worker context assembly runtime flow', 'ContextAssemblyLocalStructurePort'],
  ['apps/worker context assembly runtime flow', 'ContextAssemblyRelatedContextRetrievalPort'],
  ['apps/worker context assembly runtime flow', 'ContextAssemblyMemoryRetrievalPort'],
  ['ContextAssemblyTargetSnapshotPort', 'Turso canonical notes/sections/blocks'],
  ['ContextAssemblyLocalStructurePort', 'semantic-unit projections'],
  ['ContextAssemblyRelatedContextRetrievalPort', 'semantic-unit projections'],
  ['ContextAssemblyRelatedContextRetrievalPort', 'Turso canonical note/block excerpts'],
  ['ContextAssemblyMemoryRetrievalPort', 'memory projections'],
  ['ContextEnvelopeBuilt', 'ai-engine'],
  ['ai-engine', 'provider-registry'],
  ['provider-registry', 'operation-generation-provider'],
  ['operation-generation-provider', 'apps/worker structure job operation orchestration flow'],
  ['apps/worker structure job operation orchestration flow', 'completed StructureJob response'],
  ['completed StructureJob response', 'structure job operation flow'],
  ['structure job operation flow', 'runtime operation routing adapter'],
  ['cloudflare-agents', 'turso'],
  ['runtime operation routing adapter', 'operation-router'],
  ['operation-router', 'audit-persistence-port'],
  ['operation-router', 'operation-projection-persistence-flow'],
  ['operation-projection-persistence-flow', 'operation-projection-persistence-port'],
  ['operation-projection-persistence-flow', 'operation-proposal-persistence-port'],
  ['operation proposal accept/dismiss route handler', 'operation approval runtime handler'],
  ['operation approval runtime handler', 'operation-proposal-persistence-port'],
  ['accepted operation proposal', 'approved-intent-for-later-projection-boundary'],
  ['dismissed operation proposal', 'no-projection-or-note-block-sot-mutation'],
] as const;
